### ISSUE TITLE
topicID vs topicCID

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p-pubsub#11]
See https://github.com/libp2p/js-libp2p-pubsub/blob/master/src/message/rpc.proto.js#L9

should instances of `topicCID` be replaced with `topicID`?

**Comment by Mikerah** [comment]
According to the current [protobuf spec](https://github.com/libp2p/specs/tree/master/pubsub), I would say yes. The current protobuf definition in this repo was copied over from js-libp2p-floodsub.
