### ISSUE TITLE
Add message signing support

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p-pubsub#16]
Go is looking to turn message signing on by default and rolled out to the daemon and IPFS. The change has already been done, but the rollout process is still underway. We need to get message signing support added to js pubsub. We can do this in two phases to split up the work:

- [x] 1. Add support for message signing and sign outgoing messages by default
- [x] 2. Verify the signatures of incoming messages (before they go through validators)

Ref: https://github.com/libp2p/go-libp2p-pubsub/issues/179

**Comment by vasco-santos** [comment]
Closed by #17 and #20

**Comment by vasco-santos** [comment]
Closed by #17 and #20
