### ISSUE TITLE
Add signing and verification of messages

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p-pubsub#18]
As we go for enabling `signing` and `verification` of messages, this logic should live under the base protocol implementation, that is, the codebase of `js-libp2p-pubsub`.

This issue intends to track the refactor of `js-libp2p-pubsub`, as well as of its implementors to have these implemented in here, instead of needing to implement this in each implementation of pubsub.

**Comment by tobowers** [comment]
Doesn't this now exist? I see sign and verify in the repo.

**Comment by vasco-santos** [comment]
Already implemented
