### ISSUE TITLE
Stop should handle dials abort gracefully

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p-pubsub#21]
We currently have a bad solution for aborting dials on :[libp2p/js-libp2p-pubsub/src/index.js#L163-L166](https://github.com/libp2p/js-libp2p-pubsub/blob/master/src/index.js#L163-L166). The same also is happening in [ChainSafe/gossipsub-js](https://github.com/ChainSafe/gossipsub-js).

Basically, we are not really aborting but validating after the dial finish before continuing. This may leverage the dial abort with the async migration in libp2p

**Comment by vasco-santos** [comment]
Also

> So _dialPeer is a misnomer (we should change this in the future). We're not actually dialing the peer. This is triggered from the peer:connect event, which means we have a muxed connection to the given peer when this is called. We're not dialing to the peer, we're just negotiating the pubsub protocol.

This naming should be changed

**Comment by achingbrain** [comment]
Closing due to staleness.  Gossipsub no longer extends the class in this module.
