### ISSUE TITLE
Default value for self emit option

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p-pubsub#22]
Our `floodsub` implementation was self-emitting, pubsub messages if the node has previously subscribed to that topic. However, users may not expect this to happen and this is not clear at the moment.

In this context, I created PRs to allow this to be configurable:

[libp2p/js-libp2p-floodsub#85](https://github.com/libp2p/js-libp2p-floodsub/pull/85)
[ChainSafe/gossipsub-js#40](https://github.com/ChainSafe/gossipsub-js/pull/40)

In this context, I opened this issue for discussing whether we should continue with this default behaviour in `js-libp2p`, or change this to false.

cc @jacobheun

**Comment by a1300** [comment]
@vasco-santos related to https://github.com/libp2p/js-libp2p/issues/401

**Comment by vasco-santos** [comment]
@a1300 any opinions on keeping the default to `true` or move to false?

**Comment by a1300** [comment]
Personally I would leave the defaults for the options `signMessages` and `strictSigning` to `true` but the default for `emitSelf` I would change to `false` because I didn't expected that I would need to handle this case.

cc @vasco-santos @jacobheun

**Comment by jacobheun** [comment]
I agree that `emitSelf` should be false by default, the current default behavior is counter intuitive.

**Comment by vasco-santos** [comment]
I will work on changing that

**Comment by vasco-santos** [comment]
It defaults to `false` now both on floodsub and gossipsub
