### ISSUE TITLE
Improve abstract pubsub implementation

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p-pubsub#23]
The purpose of this module consists of being used as the base block for libp2p based pubsub routing protocols.

Currently, we have some logic on the pubsub routing protocols that can also be extracted into this module. Namely, the `emitSelf` option, message signing, among others. However, we must no be really restrictive as new protocols may not do what is currently the same for `libp2p-floodsub` and `gossipsub`.

In this context, we should draft a newer API that could help us maintaining less code and allowing easier development of new pubsub routing protocols.

cc @jacobheun

**Comment by achingbrain** [comment]
Closing due to staleness.
