### ISSUE TITLE
Pubsub Message.seqno should be 8 bytes instead of 20

### ISSUE THREAD

**Issue by Nashatyrev** [libp2p/js-libp2p-pubsub#27]
In your samples the `Message.seqno` is generated by `utils.randomSeqno()` which generates 20 bytes. 
https://github.com/libp2p/js-libp2p-pubsub/blob/165f01bb0716f53990326fd4dcf4c4b427797b2a/src/utils.js#L14

While the spec implies 8 bytes 
https://github.com/libp2p/specs/tree/master/pubsub#the-message

**Comment by vasco-santos** [comment]
Thanks for reporting this @Nashatyrev 

Would like to PR this with a fix?

**Comment by Nashatyrev** [comment]
@vasco-santos Unfortunately I'm far from JS expert and not js-libp2p user. I'm afraid that cooking a PR would take me irrational amount time :(

This is just to let you know about this inconsistency which was discovered during interop between  JS and JVM Ethereum 2.0 clients (we were on the JVM side :) )
