### ISSUE TITLE
Improve test stream mock

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p-pubsub#47]
We are currently using [alanshaw/it-pair](https://github.com/alanshaw/it-pair) for testing the pubsub implementations. This pair of {source, sink} streams is bare minimal and does not include functions like reset.

In [libp2p/js-libp2p-pubsub#45](https://github.com/libp2p/js-libp2p-pubsub/pull/45]), we added a stream reset for properly closing the read side of the stream, but we needed to add a validation if the function exists because of the tests.

We should probably create a wrapper around the `it-pair` that makes these streams similar to the multiplexex streams.

**Comment by achingbrain** [comment]
Closing due to staleness.
