### ISSUE TITLE
All rpc message processing after 'normalization'

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p-pubsub#50]
Currently, we have two slightly different representations of RPC.Message objects, named (in js-libp2p-gossipsub) [`Message`](https://github.com/ChainSafe/js-libp2p-gossipsub/blob/master/ts/message/index.ts#L28) and [`InMessage`](https://github.com/ChainSafe/js-libp2p-gossipsub/blob/master/ts/message/index.ts#L69).
The differ by their `from` property, which is a `Buffer` in `Message` and a base58-encoded `string` in `InMessage`

The strategy for creating an extensible interface has been to create a `_processX` method for each X entry in an `RPC` object, but 'normalizing' `Message` objects to `InMessage` objects before message processing.
Pseudocode for idealized RPC processing:
```typescript

function _processRPC (peer: Peer, rpc: RPC) {
  rpc.subscriptions.forEach(sub => _processSubOpt(peer, sub))
  rpc.msgs.forEach(msg => _processMessage(peer, normalize(msg)))
}

function normalize (msg: Message): InMessage {}

function _processMessage (peer: Peer, msg: InMessage): void {
  if (await validate(peer, msg)) {
    _publishMsg(peer, msg)
  }
}

async function validate (peer: Peer, msg: InMessage): Promise<boolean> {}
```

One wrinkle to getting to this ^ is the `validate` method, which still operates on `Message` objects instead of `InMessage` objects. Because of this, we end up with special handling of message validation outside of the `_processMessage` scope. See https://github.com/ChainSafe/js-libp2p-gossipsub/blob/master/ts/pubsub.js#L163-L175

The current strategy of validating messages before "processing" them leads to problems adding pre-validation processing steps.. Eg: in gossipsub, checking a seen cache or peer gray/blacklist should likely be checked before topic validation (as is done [in go-libp2p-pubsub](https://github.com/libp2p/go-libp2p-pubsub/blob/master/pubsub.go#L924)), but cannot be done within `_processMessage` when validation occurs outside.

I think the only thing to do to allow `validate` to operate on `InMessage` objects is changing the signing code to generate a PeerId/public key fromB58String instead of fromBytes. Perhaps this can be done in a backwards compatible way by checking `typeof message.from === 'string'`.
https://github.com/libp2p/js-libp2p-pubsub/blob/master/src/message/sign.js#L69

Alternatively, the message can simply be converted back to `Message` before being passed to `validate`, but this doesn't seem ideal.

**Comment by vasco-santos** [comment]
I agree that the current approach is not as flexible as it should.
When we port the pubsub base implementation from gossipsub to here, I think we can go as you suggest and create from b58. Backwards compatible validation 👍

**Comment by achingbrain** [comment]
Closing due to staleness.
