### ISSUE TITLE
Publish method signature discussion

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p-pubsub#51]
Currently, the `publish` method has two params
`topics: string[] | string` - the list of topics associated with the 'messages'
and `messages: (string | Buffer | ArrayBuffer)[] | (string | Buffer | ArrayBuffer)` - the list of data payloads to be propagated.

How come this method accepts a list of payloads instead of a single payload? (the [`Message`](https://github.com/ChainSafe/js-libp2p-gossipsub/blob/master/ts/message/index.ts#L28) object within an RPC object looks more like this shape -- a list of topics and a single data payload)

Is the intention to be able to reuse a single RPC to broadcast multiple message payloads at once?
In that case, shouldn't the interface allow something more like `{topics: string[] | string, data: string | Buffer | ArrayBuffer}[]`, which exposes the full flexibility of each `Message` object?

**Comment by vasco-santos** [comment]
I am not sure on what was the initial goal for pubsub to allow multiple messages, as this was already implemented this way on floodsub long time ago.
The wire protocol supports multiple messages (https://github.com/libp2p/js-libp2p-pubsub/blob/master/src/message/rpc.proto.js#L5) and is a wrapper for the message.

https://github.com/libp2p/js-libp2p-pubsub/blob/master/src/peer.js#L149

**Comment by wemeetagain** [comment]
Right, I guess the conflict between the interface and the wire protocol is that each message contains its own set of topics, whereas the interface conflates a single set of topics for all messages.

Its in this in-between area, where its kinda right, but ultimately is not quite connected to the wire protocol. My hope would be to align it to either the wire `Message`, or the wire `RPC`, or deprecate and provide an alternative interface which more neatly maps the underlying protocol in one of those directions.

It seems that go-libp2p-pubsub has something closely resembling the wire `Message`, `(topics: string[], data: Buffer, opts?: object)` https://github.com/libp2p/go-libp2p-pubsub/blob/master/pubsub.go#L1098
It's been deprecated for https://github.com/libp2p/go-libp2p-pubsub/blob/master/topic.go#L160 with an interface similar to `(topic: string, data: Buffer, opts?: object)`

**Comment by vasco-santos** [comment]
I think consistence is important for reducing cognitive load. It seems that `js-libp2p` is only supporting `data` to be published (https://github.com/libp2p/js-libp2p/blob/master/doc/API.md#pubsubpublish). Same for `js-ipfs` (https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/PUBSUB.md#ipfspubsubpublishtopic-data-options).

I think it would be good to change it here as well and be consistent with the APIs. @jacobheun any objection?

**Comment by jacobheun** [comment]
I think it makes sense to align this with `Message`. The js-libp2p interface currently only accepts `topic` as a string and not an array, it would be good to make these match as part of this change, there's no need for the abstraction layer there. 

If there is value in aligning it with `RPC` I think that should be done as a separate interface as that's likely not the standard use case.

**Comment by wemeetagain** [comment]
Resolved with #62
