### ISSUE TITLE
Outgoing peer connections - peer protocols

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p-pubsub#54]
See https://github.com/libp2p/js-libp2p-pubsub/blob/master/src/index.js#L190

It appears that when we connect to a new peer, we attach all protocol strings that _we_ currently support to that peer, rather than only attaching the protocol for the stream that gets opened, as is done in `_onIncomingStream`. Is this intended?

**Comment by vasco-santos** [comment]
When we have an inbound stream open (`_onIncomingStream`), we attach the stream protocol.
When we have a connection to a peer, we do not know which protocol will be negotiated. 

> we attach all protocol strings that we currently support to that peer

We attach the protocol strings provided to pubsub by the router, not all the protocols a peer is running.

The protocol strings are used for validation and fallback to floodsub, so I think this does not create any issue. Any problem you are experiencing?

**Comment by wemeetagain** [comment]
> When we have a connection to a peer, we do not know which protocol will be negotiated.

Shouldn't we wait, or populate the negotiated stream protocol when its available?

The issue is that we use `peer.protocols` to determine whether to do floodsub fallback. We're treating `peer.protocols` like the negotiated stream protocol. (in fact thats what I thought it was, before reading thru here again)

It appears that bc of this, any outgoing connection behaves like a floodsub fallback.
https://github.com/ChainSafe/js-libp2p-gossipsub/blob/master/ts/index.ts#L229

I did some deep diving yesterday on the `Peer` class. My understanding is that its primary purpose is to manage the negotiated pubsub stream. I think if possible, `protocols` should be abandoned in favor of a single `protocol`, which represents the negotiated stream protocol. This would more closely align with the output of `conn.newStream`, and be more useful, as right now there is no reliable way to determine with accuracy which protocol is actually negotiated.

**Comment by vasco-santos** [comment]
> The issue is that we use peer.protocols to determine whether to do floodsub fallback. We're treating peer.protocols like the negotiated stream protocol. (in fact thats what I thought it was, before reading thru here again)

I would not consider that because the negotiated stream protocol will just be one and we want to have multiple if we know multiple in the context of pubsub.

> I did some deep diving yesterday on the Peer class. My understanding is that its primary purpose is to manage the negotiated pubsub stream. I think if possible, protocols should be abandoned in favor of a single protocol, which represents the negotiated stream protocol. This would more closely align with the output of conn.newStream, and be more useful, as right now there is no reliable way to determine with accuracy which protocol is actually negotiated.

We can go that way, but we will need to guarantee that the protocol is updated once we know it in the peer. We can do it here when we refactor the pubsub base class from gossipsub into here.

> It appears that bc of this, any outgoing connection behaves like a floodsub fallback.
https://github.com/ChainSafe/js-libp2p-gossipsub/blob/master/ts/index.ts#L229

Meanwhile, you can simply add a condition that check if the peer does not have a gossipsub protocol, since it will be the first to be be negotiated.

**Comment by wemeetagain** [comment]
> Meanwhile, you can simply add a condition that check if the peer does not have a gossipsub protocol, since it will be the first to be be negotiated.

I don't think we know which protocols the peer supports if its an outbound connection. The `peer.protocols` is always just `this.multicodecs`, all of our pubsub protocols, rather than _their_ pubsub protocols.

**Comment by vasco-santos** [comment]
Yeah, you are right! We need to wait for the end of the `conn.newStream()` and update the peer with the unique multicodec as you suggested

**Comment by wemeetagain** [comment]
Resolved with #63
