### ISSUE TITLE
Peer class discussion

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p-pubsub#56]
It seems `Peer`s primary purpose is to manage a peer's pubsub stream and negotiated protocol.

A few suggestions to make this clearer:
- constructor should take `{ id, stream, protocol }` to align with the return values of [`conn.newStream`](https://github.com/libp2p/js-libp2p-pubsub/blob/master/src/index.js#L197) and callback attached to [`registrar.handle`](https://github.com/libp2p/js-libp2p-pubsub/blob/master/src/index.js#L172)
- rename `this.conn` to something more descriptive, possible rename `this.stream` at the same time.
In any case, it seems the object `this.conn` is actually the muxed pubsub stream and not a `Connection` object, See https://github.com/libp2p/js-libp2p-pubsub/blob/master/src/index.js#L197
- I think the `Peer` class could/should be thinner, recommend removing `topics`, `_sendRawSubscriptions`, `sendSubscriptions`, `sendUnsubscriptions`, `sendMessages`, and `updateSubscriptions`. These should likely be handled independently by router implementations. `topics` is especially troublesome, as js-libp2p-pubsub doesn't currently manage each `Peer.topics`, so this additional index must be maintained by the router.
I think ideally, any js-libp2p-pubsub-managed indices or convenience methods are placed on `src/index.js` and a `Peer` maintains a simple `write`/`close` interface.

**Comment by vasco-santos** [comment]
> constructor should take { id, stream, protocol } to align with the return values of conn.newStream and callback attached to registrar.handle

That seems good. Optional protocol? As we might want to add the peer before knowing the protocol?

> rename this.conn to something more descriptive, possible rename this.stream at the same time.
In any case, it seems the object this.conn is actually the muxed pubsub stream and not a Connection object, See https://github.com/libp2p/js-libp2p-pubsub/blob/master/src/index.js#L197

👍  totally, this is older code pre refactor, and `conn` is definitely incorrect

> I think the Peer class could/should be thinner, recommend removing topics, _sendRawSubscriptions, sendSubscriptions, sendUnsubscriptions, sendMessages, and updateSubscriptions. These should likely be handled independently by router implementations. topics is especially troublesome, as js-libp2p-pubsub doesn't currently manage each Peer.topics, so this additional index must be maintained by the router.
I think ideally, any js-libp2p-pubsub-managed indices or convenience methods are placed on src/index.js and a Peer maintains a simple write/close interface.

That seems reasonable to me. I also find strange the messages being encoded inside the peer class. I am also happy to consider renaming `peer` to something more clear

**Comment by wemeetagain** [comment]
> That seems good. Optional protocol? As we might want to add the peer before knowing the protocol?

If the `Peer` abstraction is just a wrapper around the muxed stream, I think there won't be (or shouldn't be) a case where we are creating the `Peer` before we know the stream and protocol. The protocol and stream always come together, both in incoming and outgoing cases. Might also be more clear if we rename `Peer` or add more documentation.

**Comment by wemeetagain** [comment]
Resolved with #63
