### ISSUE TITLE
Ensure compatibility with pubsub spec changes regarding messageIDs

### ISSUE THREAD

**Issue by rklaehn** [libp2p/js-libp2p-pubsub#67]
proto format for `messageIDs` in gossipsub has been changed from `string` to `bytes`. Long story, all the gory details are referenced from the PR https://github.com/libp2p/specs/pull/285 .

Js gossipsub should ensure that everything works fine with non-utf8 message ids. If that is already the case, feel free to close this issue. Just wanted to make you aware.

**Comment by vasco-santos** [comment]
@rklaehn thanks for raising this. We will be working on this together with the gossipsub1.1 update

**Comment by achingbrain** [comment]
Gossipsub message ids are bytes so all good here, I think.
