### ISSUE TITLE
Issue surrounding dropping peers

### ISSUE THREAD

**Issue by GregTheGreek** [libp2p/js-libp2p-pubsub#9]
While reviewing @Mikerah PR ChainSafeSystems/gossipsub-js/pull/15 , a specific line caught me by surprise and I'm curious on all your thoughts.

On [this line](https://github.com/ChainSafeSystems/gossipsub-js/pull/15#discussion-diff-265188638R84) we are checking if `if (--peer._references === 0)` before dropping a peer, which leads me to believe that if there was only two peers on the network they would kick each-other, meaning they would never make a connection.

Which I'm thinking might cause issues on startup if theres a latency getting peers (which if I remember correctly) eth1,x clients do have a bit of an issue with. Sometimes it takes quite a while to get peers sync'd.

**Comment by Mikerah** [comment]
In particular, the issue that Greg occurs here: https://github.com/libp2p/js-libp2p-pubsub/blob/master/src/index.js#L103.

**Comment by vasco-santos** [comment]
Thanks for reporting this @GregTheGreek ! 

Can you create a simple test in a PR that causes this issue? It would be extremely helpful for debugging

**Comment by GregTheGreek** [comment]
> Thanks for reporting this @GregTheGreek !
> 
> Can you create a simple test in a PR that causes this issue? It would be extremely helpful for debugging

Yep I'll whip something up!

**Comment by GregTheGreek** [comment]
I actually don' think this is an issue, it was my misunderstanding of how the references were created.

**Comment by vasco-santos** [comment]
All right! I will close the issue, but feel free to re-open it if needed!
